### ISSUE TITLE
Delegation-certificate in One owner and multi owner

### ISSUE THREAD

**Issue by minzak** [angelstakepool/multiowner-pool-instructions#1]
Hm, I do not fully understand,
It is step-by-step, or need choose single-owner or multi-owner variants here?

I'm interested in multi-owner variants configuration.
Before I make pool.cert for multi-owner, do I need to make pool.cert for one-owner? But why?
And I do not see what about making delegation-certificate for multi-owner, only one-owner is present here.

Thanks.

**Comment by angelstakepool** [comment]
In these steps, I cover how to add multi-owners to a pool.  

The 1st step is JUST to create the pool using a normal CLI address as the owner and to pay the 500 ADA deposit.  Then all the would-be owners will delegate to this pool from their own hardware wallets (my steps explain ledger) using any light wallet such as ETERNL.  

After that, you would need to create another cert in which you add all these owners (using their hardware wallets public staking key), and each of them would need to sign this tx by generating a witness.  At the end, you would gather all these witnesses and assemble them and then submit the signed multi-witness tx

hope this helps
